global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

# Alert manager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Rule files
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# Scrape configurations
scrape_configs:
  - job_name: "litellm"
    metrics_path: "/metrics"
    scheme: http
    static_configs:
      - targets: ["litellm:4000"]
        labels:
          service: "litellm-proxy"
          environment: "production"

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          service: "prometheus"
          environment: "production"

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
        labels:
          service: "node-metrics"
          environment: "production"
    # Uncomment below if you add node-exporter to your setup

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
        labels:
          service: "container-metrics"
          environment: "production"
    # Uncomment above if you add cadvisor to your setup for container metrics